cs481-ekh/f22-viz-kids

- src/App.tsx
- src/RenderView.tsx
Uses dummy data for now, to be updated later when we have a way to set a data source
Camera position is probably also not great
> Initial work on point rendering

- src/DataTypes.ts
- src/Parser.ts
> prepare types to implement parseForceFileData

- src/Parser.ts
> implemented parseForceFileData

- package-lock.json
- package.json
- src/App.tsx
> add file uploader #54

- src/App.scss
- src/App.tsx
Some of the later additions from sprint 1 would benefit from a little refactoring to make it easier to build upon for sprint 2.
> refactor app and stylesheet

- src/App.tsx
For now, plays the animation once as soon as markers are loaded. To be improved in #100
> Initial implementation of animation

- src/RenderView.tsx
Pretty self-explanatory. Grid is 30 meters x 30 meters, with 1 meter squares.
> add ground plane grid

- src/RenderView.tsx
The helper's axes are colored R, G, B to signify COBR's x, y, z axes.
> add axis helper

- package-lock.json
- src/App.tsx
Closes #114
Slider moves according to current frame and manual timeline. Slider can now also control current frame.
> Added Timeline-Track Functionality

- src/App.scss
Closes #113 
Confirmed style is correct with Firefox, Microsoft Edge and Google Chrome
> Added track compatibility with Firefox

- src/App.tsx
> Fixed issues with text input frames

- src/App.tsx
- src/RenderView.tsx
Consolidates and refactors a few unfinished implementations (#118, #120, #134) to close out story #90 before sponsor demo this upcoming Monday.
> finish force vector rendering

- src/App.tsx
- src/SelectionInfoView.tsx
Closes #138 
includes #147 for now to see what happens when that gets merged
> Show marker metadata in Selection Info area

- src/Calculations.ts
- src/DataTypes.ts
- src/Parser.ts
- src/RenderView.tsx
- test/Parser.test.ts
Moves NaN checks into the parser and replaces MIME type checks.
> Refactor parser

- src/SelectionInfoView.tsx
> Implement marker tri-selection and display angle calculation 

- src/Calculations.ts
- test/Calculations.test.ts
Probably will need tweaks but these results seem reasonable for the one sample file we have (173, 448)
Test currently calls the parser but we might want to not do that since this isn't a parser test
> Implement initial version of gait event suggestion calculation

- src/dataTypes.ts
- src/modules/Parser.ts
- test/Parser.test.ts
- Did not take long just needed research about how torque works
- based off some research if we want torque visualization its based in a 3D point
- https://cfm2019.sciencesconf.org/245628/document
- above is a link to open sim research paper showing torque on force plates
> 195 add torque visualization foundation

- src/App.scss
- src/App.tsx
- src/views/TimelineTextView.tsx
- src/views/TimelineTrackView.tsx
> framespeed controls

- src/modules/Parser.ts
- test/Parser.test.ts
I didn't catch this off by one error when I reviewed #196 which has been merged
> fix torque column off by one

- src/App.scss
- src/App.tsx
- src/views/PopupView.tsx
- src/views/RenderView.tsx
Adds menu option for turning body segments on and off
> toggle segments

- src/App.scss
- src/views/TimelineTrackView.tsx
Closes #180 
Button and positions are set, no functionality yet.
> Added button placeholders

- src/App.tsx
- src/views/SelectionInfoView.tsx
> 200 fix bug in torque display

- src/App.scss
- src/App.tsx
- src/views/TimelineTrackView.tsx
> Buttons integrated according to Gait Suggestions

- src/modules/Export.ts
- test/Export.test.ts
Function to be used in the UI later
> Implement angle export processing

- src/views/PopupView.tsx
> Added timeline controls image to main menu

- src/App.scss
- src/views/PopupView.tsx
> add help info

- .dockerignore
- Dockerfile
- build.sh
Closes #223 
exposed on port 80 from the container
> Add Dockerfile
